from __future__ import annotations
import torch
import torch.nn.functional as F


def dice_loss(prob: torch.Tensor, target: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    prob = prob.float(); target = target.float()
    dims = tuple(range(2, prob.ndim))
    inter = (prob * target).sum(dims)
    den = prob.sum(dims) + target.sum(dims)
    return (1 - (2 * inter + eps) / (den + eps)).mean()


def masked_mse(pred: torch.Tensor, target: torch.Tensor, mask: torch.Tensor | None = None, weight: torch.Tensor | None = None) -> torch.Tensor:
    loss = (pred - target) ** 2
    if weight is not None:
        loss = loss * weight
    if mask is not None:
        loss = loss * mask
        return loss.sum() / (mask.sum() + 1e-6)
    return loss.mean()


def cfc_loss(seg_encoding: torch.Tensor, det_encoding: torch.Tensor) -> torch.Tensor:
    return F.mse_loss(seg_encoding, det_encoding.detach())


def dynamic_loss(seg_logits: torch.Tensor, det_prob: torch.Tensor, pseudo: torch.Tensor, has_pseudo: torch.Tensor | None = None) -> torch.Tensor:
    """Interactive supervision loss.

    `pseudo` must be a dense pseudo mask generated by source-HoVerNet bootstrap
    or CPL. Sparse point annotations should not be passed as pseudo masks.
    If `has_pseudo` is all zeros, this function returns zero and disables Ldyn.
    """
    if seg_logits.shape[-2:] != pseudo.shape[-2:]:
        pseudo = F.interpolate(pseudo.float(), size=seg_logits.shape[-2:], mode="nearest")
        if has_pseudo is not None:
            has_pseudo = F.interpolate(has_pseudo.float(), size=seg_logits.shape[-2:], mode="nearest")

    if has_pseudo is not None and has_pseudo.sum() <= 0:
        return seg_logits.sum() * 0.0

    seg_ce_map = F.cross_entropy(seg_logits, pseudo.squeeze(1).long(), reduction="none")[:, None]
    if has_pseudo is not None:
        seg_ce = (seg_ce_map * has_pseudo).sum() / (has_pseudo.sum() + 1e-6)
    else:
        seg_ce = seg_ce_map.mean()

    if det_prob.shape[-2:] != pseudo.shape[-2:]:
        det_prob = F.interpolate(det_prob, size=pseudo.shape[-2:], mode="bilinear", align_corners=False)
    det_mse_map = (det_prob - pseudo.float()) ** 2
    if has_pseudo is not None:
        det_mse = (det_mse_map * has_pseudo).sum() / (has_pseudo.sum() + 1e-6)
    else:
        det_mse = det_mse_map.mean()
    return seg_ce + det_mse


def hover_supervised_loss(outputs: dict[str, torch.Tensor], np_target: torch.Tensor, hv_target: torch.Tensor) -> torch.Tensor:
    if outputs["np"].shape[-2:] != np_target.shape[-2:]:
        np_target = F.interpolate(np_target.float(), size=outputs["np"].shape[-2:], mode="nearest")
        hv_target = F.interpolate(hv_target.float(), size=outputs["hv"].shape[-2:], mode="bilinear", align_corners=False)
    np_logits = outputs["np"]
    np_prob = torch.softmax(np_logits, dim=1)[:, 1:2]
    ce = F.cross_entropy(np_logits, np_target.squeeze(1).long())
    dice = dice_loss(np_prob, np_target.float())
    hv_mse = F.mse_loss(outputs["hv"], hv_target.float())
    return ce + dice + hv_mse
